from typing import Any

class Redis:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def ping(self) -> bool: ...
    def get(self, key: Any) -> Any: ...
    def set(self, key: Any, value: Any, ex: int | None = ...) -> None: ...
    def info(self) -> dict[str, Any]: ...
    def dbsize(self) -> int: ...
    def scan(self, cursor: Any, match: str | None = ..., count: int | None = ...) -> tuple[Any, list[Any]]: ...
    def delete(self, *keys: Any) -> int: ...
    def flushdb(self) -> None: ...
    def close(self) -> None: ...

__all__ = ["Redis"]
