from typing import Any, Iterable, Iterator, Mapping


class ResponseError(Exception):
    ...


class ConnectionPool:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def disconnect(self) -> None: ...


class Redis:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def ping(self) -> bool: ...
    def get(self, name: str, /) -> Any | None: ...
    def set(self, name: str, value: Any, /, *, ex: int | None = ...) -> bool: ...
    def setex(self, name: str, time: int, value: Any) -> bool: ...
    def ttl(self, name: str, /) -> int: ...
    def expire(self, name: str, time: int) -> bool: ...
    def hset(self, name: str, key: str, value: Any) -> int: ...
    def hget(self, name: str, key: str) -> Any | None: ...
    def hdel(self, name: str, *keys: str) -> int: ...
    def keys(self, pattern: str = "*") -> Iterable[str]: ...
    def scan_iter(self, match: str | None = ..., count: int | None = ...) -> Iterator[str]: ...
    def delete(self, *names: str) -> int: ...
    def info(self, section: str | None = ...) -> Mapping[str, Any]: ...
    def flushdb(self) -> bool: ...
    def dbsize(self) -> int: ...
    def pipeline(self) -> "RedisPipeline": ...
    def close(self) -> None: ...


class RedisPipeline:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def hset(self, name: str, key: str, value: Any) -> "RedisPipeline": ...
    def expire(self, name: str, time: int) -> "RedisPipeline": ...
    def execute(self) -> list[Any]: ...


class exceptions:
    ResponseError = ResponseError


__all__ = ["Redis", "RedisPipeline", "ResponseError", "ConnectionPool", "exceptions"]
