from typing import Any, Awaitable, Protocol

class AsyncCursor(Protocol):
    async def fetchall(self) -> list[Any]: ...
    async def fetchone(self) -> Any: ...
    async def close(self) -> None: ...

class AsyncConnection(Protocol):
    async def cursor(self) -> AsyncCursor: ...
    async def close(self) -> None: ...

    @classmethod
    def connect(cls, dsn: str, /, **kwargs: Any) -> Awaitable[AsyncConnection]: ...

class SyncConnection(Protocol):
    def cursor(self) -> Any: ...
    def close(self) -> None: ...

class psycopg(Protocol):
    AsyncConnection: type[AsyncConnection]
    Connection: type[SyncConnection]

__all__ = ["AsyncConnection", "AsyncCursor", "SyncConnection"]
