from typing import Any, Awaitable, Iterator, Protocol

class AsyncCursor(Protocol):
    async def __aenter__(self) -> "AsyncCursor": ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any | None) -> bool | None: ...
    async def execute(self, query: Any, *args: Any, **kwargs: Any) -> Any: ...
    async def fetchall(self) -> list[Any]: ...
    async def fetchone(self) -> Any: ...
    async def close(self) -> None: ...


class AsyncCursorManager(Protocol):
    def __await__(self) -> Iterator[AsyncCursor]: ...
    async def __aenter__(self) -> AsyncCursor: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any | None) -> bool | None: ...


class AsyncConnection(Protocol):
    async def __aenter__(self) -> "AsyncConnection": ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any | None) -> bool | None: ...
    def cursor(self) -> AsyncCursorManager: ...
    async def close(self) -> None: ...

    @classmethod
    def connect(cls, dsn: str | None = ..., **kwargs: Any) -> Awaitable[AsyncConnection]: ...

class SyncConnection(Protocol):
    def cursor(self) -> Any: ...
    def close(self) -> None: ...

class psycopg(Protocol):
    AsyncConnection: type[AsyncConnection]
    Connection: type[SyncConnection]

__all__ = ["AsyncConnection", "AsyncCursor", "AsyncCursorManager", "SyncConnection"]
