from typing import Any, Awaitable, Protocol


class _AsyncCursor(Protocol):
    async def __aenter__(self) -> Any: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    def execute(self, query: str, *args: Any, **kwargs: Any) -> Any: ...
    def fetchone(self) -> Any: ...
    def close(self) -> None: ...


class AsyncConnection:
    @classmethod
    async def connect(cls, dsn: str, *args: Any, **kwargs: Any) -> "AsyncConnection": ...

    async def __aenter__(self) -> "AsyncConnection": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def execute(self, query: str, *args: Any, **kwargs: Any) -> Any: ...
    def cursor(self) -> _AsyncCursor: ...
    def close(self) -> None: ...


def connect(dsn: str, *args: Any, **kwargs: Any) -> Awaitable[AsyncConnection]: ...


__all__ = ["AsyncConnection", "connect"]
