from __future__ import annotations
from typing import Any, Iterable, Iterator, Sequence, TypeVar, overload

_T = TypeVar("_T")

class dtype:
    def __init__(self, obj: Any = ..., *, align: bool = ..., copy: bool = ...) -> None: ...

class ndarray:
    shape: tuple[int, ...]
    dtype: dtype
    def __array__(self) -> "ndarray": ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, item: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __abs__(self) -> "ndarray": ...
    def __add__(self, other: Any) -> "ndarray": ...
    def __radd__(self, other: Any) -> "ndarray": ...
    def __sub__(self, other: Any) -> "ndarray": ...
    def __rsub__(self, other: Any) -> "ndarray": ...
    def __mul__(self, other: Any) -> "ndarray": ...
    def __rmul__(self, other: Any) -> "ndarray": ...
    def __truediv__(self, other: Any) -> "ndarray": ...
    def __rtruediv__(self, other: Any) -> "ndarray": ...
    def astype(self, dtype: Any, *, copy: bool = ...) -> "ndarray": ...
    def mean(self, axis: Any = ..., dtype: Any = ..., keepdims: bool = ...) -> Any: ...
    def max(self, axis: Any = ..., keepdims: bool = ...) -> Any: ...
    def min(self, axis: Any = ..., keepdims: bool = ...) -> Any: ...
    def sum(self, axis: Any = ..., dtype: Any = ..., keepdims: bool = ...) -> Any: ...
    def cumsum(self, axis: Any | None = ...) -> "ndarray": ...

@overload
def array(obj: Iterable[_T], dtype: Any | None = ..., copy: bool | None = ..., order: str | None = ..., subok: bool | None = ..., ndmin: int = ...) -> ndarray: ...

@overload
def array(obj: Any, dtype: Any | None = ..., copy: bool | None = ..., order: str | None = ..., subok: bool | None = ..., ndmin: int = ...) -> ndarray: ...

def asarray(obj: Any, dtype: Any | None = ..., order: str | None = ...) -> ndarray: ...
def zeros(shape: Any, dtype: Any | None = ..., order: str | None = ...) -> ndarray: ...
def ones(shape: Any, dtype: Any | None = ..., order: str | None = ...) -> ndarray: ...
def arange(start: Any, stop: Any | None = ..., step: Any | None = ..., dtype: Any | None = ...) -> Any: ...
def mean(a: Any, axis: Any = ..., dtype: Any = ..., keepdims: bool = ...) -> Any: ...
def std(a: Any, axis: Any = ..., ddof: int = ..., keepdims: bool = ...) -> Any: ...

float64 = dtype
float32 = dtype
int64 = dtype
int32 = dtype

def datetime64(*args: Any, **kwargs: Any) -> Any: ...
def timedelta64(*args: Any, **kwargs: Any) -> Any: ...

def sqrt(x: Any) -> Any: ...
def log(x: Any) -> Any: ...
def sum(a: Any, axis: Any = ..., dtype: Any = ..., keepdims: bool = ...) -> Any: ...

def concatenate(arrays: Sequence[Any], axis: int | None = ..., dtype: Any | None = ...) -> ndarray: ...

def clip(a: Any, a_min: Any, a_max: Any, out: Any = ...) -> Any: ...

def diff(a: Any, n: int = ..., axis: int = ...) -> Any: ...
def cumsum(a: Any, axis: int | None = ...) -> Any: ...
def abs(a: Any) -> Any: ...
def exp(a: Any) -> Any: ...
def dot(a: Any, b: Any) -> Any: ...

class _RandomModule:
    def seed(self, seed: int | None = ...) -> None: ...
    def randn(self, *shape: int) -> Any: ...
    def rand(self, *shape: int) -> Any: ...
    def random(self, *shape: int) -> Any: ...
    def randint(self, low: int, high: int | None = ..., size: Any = ..., dtype: Any = ...) -> Any: ...

random: _RandomModule

float_ = float

nan: float

__all__ = ["array", "asarray", "ndarray", "dtype", "zeros", "ones", "mean", "std", "sum", "concatenate", "clip", "diff", "float64", "float32", "int64", "int32", "datetime64", "timedelta64", "sqrt", "log"]
