from typing import Any, Mapping, Sequence

class DuckDBPyRelation:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def df(self) -> Any: ...

class DuckDBPyConnection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self) -> None: ...
    def cursor(self) -> "DuckDBPyConnection": ...
    def execute(
        self, query: str, parameters: Sequence[Any] | Mapping[str, Any] | None = ...
    ) -> DuckDBPyRelation: ...

def connect(database: str | None = ..., read_only: bool = ...) -> DuckDBPyConnection: ...

__all__ = ["DuckDBPyConnection", "DuckDBPyRelation", "connect"]
