from typing import Any

class Fernet:
    @staticmethod
    def generate_key() -> bytes: ...
    def __init__(self, key: bytes) -> None: ...
    def encrypt(self, data: bytes) -> bytes: ...
    def decrypt(self, token: bytes, ttl: int | None = ...) -> bytes: ...

__all__ = ["Fernet"]
