from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from dataclasses import dataclass
from typing import Any, Optional

import asyncpg
from sqlalchemy.ext.asyncio import AsyncEngine


class PoolStatisticsPayload(dict[str, Any]):
    ...


class AsyncpgPoolStatus(dict[str, Any]):
    ...


class OptimizedPoolStatisticsPayload(PoolStatisticsPayload):
    ...


class SqlAlchemyPoolStatus(dict[str, Any]):
    ...


class SqlAlchemyPoolStatisticsPayload(PoolStatisticsPayload):
    ...


@dataclass
class PoolConfig:
    dsn: str
    min_size: int = ...
    max_size: int = ...
    max_queries: int = ...
    max_inactive_connection_lifetime: float = ...
    ssl: Any = ...
    command_timeout: float = ...


@dataclass
class PoolStatistics:
    total_queries: int = ...
    failed_queries: int = ...
    total_connections: int = ...
    reused_connections: int = ...
    wait_events: int = ...

    def to_dict(self) -> dict[str, Any]: ...


class OptimizedDatabasePool:
    config: PoolConfig
    pool: asyncpg.Pool | None
    statistics: PoolStatistics

    def __init__(self, config: PoolConfig) -> None: ...

    async def initialize(self) -> None: ...

    async def acquire(self) -> AsyncIterator[asyncpg.Connection]: ...

    async def execute(self, query: str, *args: Any, timeout: float | None = ...) -> Any: ...

    async def fetch(self, query: str, *args: Any, timeout: float | None = ...) -> list[asyncpg.Record]: ...

    async def fetchval(self, query: str, *args: Any, timeout: float | None = ...) -> Any: ...

    async def fetchrow(self, query: str, *args: Any, timeout: float | None = ...) -> Optional[asyncpg.Record]: ...

    async def execute_batch(self, queries: Sequence[tuple[Any, ...]]) -> list[list[asyncpg.Record] | None]: ...

    async def execute_many(self, query: str, args_list: Sequence[tuple[Any, ...]]) -> None: ...

    async def copy_records_to_table(
        self,
        table_name: str,
        *,
        records: Sequence[tuple[Any, ...]],
        columns: Sequence[str],
        schema_name: str | None = ...,
    ) -> int: ...

    async def health_check(self) -> bool: ...

    def get_pool_status(self) -> AsyncpgPoolStatus: ...

    def get_statistics(self) -> OptimizedPoolStatisticsPayload: ...

    async def close(self) -> None: ...


class SQLAlchemyOptimizedPool:
    engine: AsyncEngine | None

    def __init__(self, url: str, *, echo: bool = ..., future: bool = ...) -> None: ...

    async def initialize(self) -> None: ...

    async def close(self) -> None: ...
