"""
WebUI API 复用数据模型。

集中维护 TypedDict、Literal 及类型别名，便于各模块共享一致的结构定义。
"""

from .capabilities import (
    CapabilityAlternative,
    CapabilityAvailabilityData,
    CapabilityAvailabilityResponse,
    CapabilityCategoryMeta,
    CapabilityCategorySummary,
    CapabilityComparisonEntry,
    CapabilityComparisonData,
    CapabilityComparisonResponse,
    CapabilityDescriptor,
    CapabilityDiffStats,
    CapabilityInfo,
    CapabilityItem,
    CapabilityMatrix,
    CapabilityMatrixCategory,
    CapabilityMatrixResponse,
    CapabilityRecommendation,
    CapabilityRecommendationData,
    CapabilityRecommendationResponse,
    CapabilitySourceInfo,
    CapabilitySummary,
    CapabilitySummaryData,
    CapabilitySummaryResponse,
    CAPABILITY_STATUS_SUCCESS,
    DataSourceSlug,
    SourceCapabilitySummary,
    SourceOverview,
    SourceMetadata,
)
from .rate_limit import RateLimitSnapshot, RateLimitStatsError, RateLimitStatsPayload
from .server import (
    ConfigValue,
    LifespanModeLiteral,
    LogLevelLiteral,
    LoopImplementationLiteral,
    ServerConfigOverrides,
    WebServerConfig,
    WebSocketImplementationLiteral,
)

__all__ = [
    "CAPABILITY_STATUS_SUCCESS",
    "CapabilityAlternative",
    "CapabilityAvailabilityData",
    "CapabilityAvailabilityResponse",
    "CapabilityCategoryMeta",
    "CapabilityCategorySummary",
    "CapabilityComparisonEntry",
    "CapabilityComparisonData",
    "CapabilityComparisonResponse",
    "CapabilityDescriptor",
    "CapabilityDiffStats",
    "CapabilityInfo",
    "CapabilityItem",
    "CapabilityMatrix",
    "CapabilityMatrixCategory",
    "CapabilityMatrixResponse",
    "CapabilityRecommendation",
    "CapabilityRecommendationData",
    "CapabilityRecommendationResponse",
    "CapabilitySourceInfo",
    "CapabilitySummary",
    "CapabilitySummaryData",
    "CapabilitySummaryResponse",
    "DataSourceSlug",
    "RateLimitSnapshot",
    "RateLimitStatsError",
    "RateLimitStatsPayload",
    "ServerConfigOverrides",
    "ConfigValue",
    "LogLevelLiteral",
    "WebSocketImplementationLiteral",
    "LoopImplementationLiteral",
    "LifespanModeLiteral",
    "WebServerConfig",
    "SourceCapabilitySummary",
    "SourceOverview",
    "SourceMetadata",
]
