from typing import Any


class Live:
    def __init__(self, renderable: Any, *, refresh_per_second: float | None = None, console: Any | None = None) -> None: ...

    def update(self, renderable: Any) -> None: ...

    def __enter__(self) -> "Live": ...

    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any | None) -> None: ...
