from typing import Any


class Progress:
    def __init__(self, *columns: Any, console: Any | None = None) -> None: ...

    def add_task(self, description: str, total: float | None = None) -> Any: ...

    def __enter__(self) -> "Progress": ...

    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any | None) -> None: ...


class SpinnerColumn:
    ...


class TextColumn:
    def __init__(self, text_format: str) -> None: ...
