from typing import Any


def plot(*args: Any, **kwargs: Any) -> Any: ...


def show(*args: Any, **kwargs: Any) -> None: ...


def figure(*args: Any, **kwargs: Any) -> Any: ...


def subplots(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...


def tight_layout(*args: Any, **kwargs: Any) -> None: ...


def savefig(*args: Any, **kwargs: Any) -> None: ...


def close(*args: Any, **kwargs: Any) -> None: ...


def ioff() -> Any: ...
