from typing import Any

def plot(*args: Any, **kwargs: Any) -> Any: ...
def show(*args: Any, **kwargs: Any) -> None: ...
def figure(*args: Any, **kwargs: Any) -> Any: ...
def subplots(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...
def subplot(*args: Any, **kwargs: Any) -> Any: ...
def bar(*args: Any, **kwargs: Any) -> Any: ...
def xlabel(*args: Any, **kwargs: Any) -> None: ...
def ylabel(*args: Any, **kwargs: Any) -> None: ...
def title(*args: Any, **kwargs: Any) -> None: ...
def xticks(*args: Any, **kwargs: Any) -> Any: ...
def legend(*args: Any, **kwargs: Any) -> Any: ...
def tight_layout(*args: Any, **kwargs: Any) -> None: ...
def savefig(*args: Any, **kwargs: Any) -> None: ...
def close(*args: Any, **kwargs: Any) -> None: ...
def ioff() -> Any: ...
