from typing import Any, Optional

class Response:
    status_code: int
    text: str
    def json(self) -> Any: ...

class Session:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    def post(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    def close(self) -> None: ...

class adapters:
    class HTTPAdapter:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class exceptions:
    class RequestException(Exception):
        ...

def get(url: str, *args: Any, **kwargs: Any) -> Response: ...
def post(url: str, *args: Any, **kwargs: Any) -> Response: ...

__all__ = ["Session", "Response", "get", "post", "adapters", "exceptions"]
