from typing import Any, Iterable

class Cursor:
    async def execute(self, query: str, parameters: Iterable[Any] | None = ...) -> None: ...
    async def fetchone(self) -> tuple[Any, ...] | None: ...

class Connection:
    async def execute(self, query: str, parameters: Iterable[Any] | None = ...) -> Cursor: ...
    async def close(self) -> None: ...

async def connect(path: str, *args: Any, **kwargs: Any) -> Connection: ...

__all__ = ["Connection", "Cursor", "connect"]
