from typing import Any


class Cursor:
    async def execute(self, query: str, *args: Any) -> None: ...
    async def fetchone(self) -> tuple[Any, ...] | None: ...
    async def close(self) -> None: ...


class Connection:
    async def cursor(self) -> Cursor: ...
    def close(self) -> None: ...


async def connect(*args: Any, **kwargs: Any) -> Connection: ...


__all__ = ["Connection", "Cursor", "connect"]
