"""Strategy interfaces module."""

from deepsearch.strategies.interfaces.base import BaseStrategy
from deepsearch.strategies.interfaces.models import (
    AggregationMethod,
    CompositeSignal,
    CompositeStrategy,
    ScreeningRequest,
    ScreeningResponse,
    ScreeningResult,
    SignalDirection,
    StrategyCategory,
    StrategyListResponse,
    StrategyMeta,
    StrategyParamDef,
    StrategyStatus,
    StrategyWeight,
    TradingCostConfig,
    TTradingConfig,
    TTradingRecord,
    TTradingSignal,
    TTradingStats,
)

__all__ = [
    "BaseStrategy",
    "StrategyMeta",
    "StrategyParamDef",
    "StrategyCategory",
    "StrategyStatus",
    "StrategyWeight",
    "StrategyListResponse",
    "CompositeStrategy",
    "CompositeSignal",
    "SignalDirection",
    "AggregationMethod",
    "ScreeningRequest",
    "ScreeningResponse",
    "ScreeningResult",
    "TTradingConfig",
    "TTradingSignal",
    "TTradingRecord",
    "TTradingStats",
    "TradingCostConfig",
]
