from typing import Any, Awaitable, Callable, Mapping, Optional

class Response:
    status_code: int
    text: str
    json: Callable[[], Any]

class AsyncClient:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def get(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    async def post(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    async def put(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    async def delete(self, url: str, *args: Any, **kwargs: Any) -> Response: ...
    async def __aenter__(self) -> "AsyncClient": ...
    async def __aexit__(self, exc_type, exc, tb) -> Optional[bool]: ...
    async def aclose(self) -> None: ...

__all__ = ["AsyncClient", "Response"]
