from __future__ import annotations

from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import Any, Optional

import asyncpg
from sqlalchemy.ext.asyncio import AsyncEngine

@dataclass
class PoolConfig:
    database_url: str
    pool_size: int = ...
    max_overflow: int = ...
    pool_timeout: float = ...
    pool_recycle: float = ...
    echo: bool = ...

@dataclass
class PoolStatistics:
    total_queries: int = ...
    failed_queries: int = ...
    total_connections: int = ...
    reused_connections: int = ...
    wait_events: int = ...

    def to_dict(self) -> dict[str, Any]: ...

class OptimizedDatabasePool:
    config: PoolConfig
    pool: Any
    engine: AsyncEngine | None
    session_factory: Any
    statistics: PoolStatistics

    def __init__(self, config: PoolConfig) -> None: ...
    async def initialize(self) -> None: ...
    async def acquire(self) -> AsyncIterator[asyncpg.Connection]: ...
    async def execute(self, query: str, *args: Any, timeout: float | None = ...) -> Any: ...
    async def fetch(
        self, query: str, *args: Any, timeout: float | None = ...
    ) -> list[asyncpg.Record]: ...
    async def fetchval(self, query: str, *args: Any, timeout: float | None = ...) -> Any: ...
    async def fetchrow(
        self, query: str, *args: Any, timeout: float | None = ...
    ) -> Optional[asyncpg.Record]: ...
    async def close(self) -> None: ...
