from typing import Any, Callable, Iterable, Iterator, Mapping, MutableMapping, Optional, Protocol

FormatFunction = Callable[["Record"], str]

class Record(MutableMapping[str, Any]):
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class Level:
    name: str

class _BindLogger(Protocol):
    def bind(self, **kwargs: Any) -> "Logger": ...

class _OptLogger(Protocol):
    def __call__(self, *args: Any, **kwargs: Any) -> "Logger": ...

class Logger:
    def debug(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def info(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def success(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def exception(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def trace(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def log(self, level: Any, message: str, *args: Any, **kwargs: Any) -> None: ...
    def bind(self, **kwargs: Any) -> "Logger": ...
    def opt(self, *args: Any, **kwargs: Any) -> "Logger": ...
    def catch(
        self, *args: Any, **kwargs: Any
    ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def add(
        self,
        sink: Any,
        level: Any = ...,
        format: Optional[str | FormatFunction] = ...,
        filter: Optional[Mapping[str, Any]] = ...,
        enqueue: bool = ...,
        colorize: bool = ...,
        backtrace: bool = ...,
        diagnose: bool = ...,
        serialize: bool = ...,
        **kwargs: Any,
    ) -> int: ...
    def remove(self, handler_id: int = ...) -> None: ...
    def configure(
        self,
        *,
        handlers: Iterable[Mapping[str, Any]] | None = ...,
        levels: Iterable[Mapping[str, Any]] | None = ...,
        extra: Mapping[str, Any] | None = ...,
    ) -> None: ...
    def level(self, name: str) -> Level: ...

logger: Logger
