from typing import Any, Callable, Iterable, Mapping, MutableMapping, Optional, Protocol

class _BindLogger(Protocol):
    def bind(self, **kwargs: Any) -> "Logger": ...

class _OptLogger(Protocol):
    def __call__(self, *args: Any, **kwargs: Any) -> "Logger": ...

class Logger:
    level: str
    def debug(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def info(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def success(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def exception(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def trace(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def log(self, level: Any, message: str, *args: Any, **kwargs: Any) -> None: ...
    def bind(self, **kwargs: Any) -> "Logger": ...
    def opt(self, *args: Any, **kwargs: Any) -> "Logger": ...
    def catch(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def add(
        self,
        sink: Any,
        level: Any = ...,
        format: Optional[str] = ...,
        filter: Optional[Mapping[str, Any]] = ...,
        enqueue: bool = ...,
        colorize: bool = ...,
        backtrace: bool = ...,
        diagnose: bool = ...,
        serialize: bool = ...,
        **kwargs: Any,
    ) -> int: ...
    def remove(self, handler_id: int = ...) -> None: ...

logger: Logger
