from typing import Any
from .. import Redis as _RedisBase

class RedisAsync(_RedisBase):
    async def ping(self) -> bool: ...
    async def get(self, key: Any) -> Any: ...
    async def set(self, key: Any, value: Any, ex: int | None = ...) -> None: ...
    async def info(self) -> dict[str, Any]: ...
    async def dbsize(self) -> int: ...
    async def scan(self, cursor: Any, match: str | None = ..., count: int | None = ...) -> tuple[Any, list[Any]]: ...
    async def delete(self, *keys: Any) -> int: ...
    async def flushdb(self) -> None: ...
    async def close(self) -> None: ...
    async def aclose(self) -> None: ...

async def from_url(url: str, *args: Any, **kwargs: Any) -> RedisAsync: ...

class Redis(RedisAsync):
    ...

__all__ = ["RedisAsync", "Redis", "from_url"]
