from typing import Any, Awaitable, Iterable
from typing import Set as SetType

def from_url(url: str, *args: Any, **kwargs: Any) -> "Redis": ...

class ConnectionPool:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def disconnect(self) -> None: ...

class Redis:
    connection_pool: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def from_url(cls, url: str, *args: Any, **kwargs: Any) -> "Redis": ...
    def ping(self) -> Awaitable[bool]: ...
    def info(self) -> Awaitable[dict[str, Any]]: ...
    def get(self, name: str, /) -> Awaitable[Any | None]: ...
    def set(self, name: str, value: Any, /, *, ex: int | None = ...) -> Awaitable[bool]: ...
    def setex(self, name: str, time: int, value: Any) -> Awaitable[bool]: ...
    def delete(self, *names: str | bytes) -> Awaitable[int]: ...
    def keys(self, pattern: str = "*") -> Awaitable[list[str]]: ...
    def scan_iter(
        self, match: str | None = ..., count: int | None = ...
    ) -> Awaitable[Iterable[str]]: ...
    def scan(
        self, cursor: int = ..., match: str | None = ..., count: int | None = ...
    ) -> Awaitable[tuple[int, list[str]]]: ...
    def expire(self, name: str, time: int) -> Awaitable[bool]: ...
    def close(self) -> None: ...
    def aclose(self) -> Awaitable[None]: ...
    def wait_closed(self) -> Awaitable[None]: ...
    # Set operations
    def sadd(self, name: str, *values: Any) -> Awaitable[int]: ...
    def smembers(self, name: str) -> Awaitable[SetType[Any]]: ...
    def srem(self, name: str, *values: Any) -> Awaitable[int]: ...
    def sismember(self, name: str, value: Any) -> Awaitable[bool]: ...
    def scard(self, name: str) -> Awaitable[int]: ...

__all__ = ["ConnectionPool", "Redis"]
