from typing import Any, AsyncIterator, Awaitable


class RedisAsync:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def ping(self) -> bool: ...
    async def get(self, key: Any) -> Any: ...
    async def set(self, key: Any, value: Any, ex: int | None = ...) -> bool: ...
    async def setex(self, name: Any, time: Any, value: Any) -> bool: ...
    async def info(self) -> dict[str, Any]: ...
    async def dbsize(self) -> int: ...
    async def scan(self, cursor: Any, match: str | None = ..., count: int | None = ...) -> tuple[Any, list[Any]]: ...
    async def scan_iter(self, match: str | None = ..., count: int | None = ...) -> AsyncIterator[Any]: ...
    async def delete(self, *keys: Any) -> int: ...
    async def flushdb(self) -> None: ...
    async def close(self) -> None: ...
    async def aclose(self) -> None: ...

    def pipeline(self, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...


class Redis(RedisAsync):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


async def from_url(url: str, *args: Any, **kwargs: Any) -> Redis:
    ...


__all__ = ["RedisAsync", "Redis", "from_url"]
