from typing import Any, Mapping, Sequence


class AkShareDirectService:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def get_realtime_quotes(self, symbols: Sequence[str]) -> Mapping[str, Any]: ...
    async def get_history_data(
        self, symbol: str, start: str | None = ..., end: str | None = ...
    ) -> Sequence[Mapping[str, Any]]: ...
