from typing import Any, Mapping, Sequence


class EastMoneyService:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def get_market_summary(self) -> Mapping[str, Any]: ...
    async def get_sector_overview(self) -> Sequence[Mapping[str, Any]]: ...
