from typing import Any, Mapping, Sequence


class MarketService:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def get_market_overview(self) -> Mapping[str, Any]: ...
    async def get_top_gainers(self, limit: int = ...) -> Sequence[Mapping[str, Any]]: ...
    async def get_top_losers(self, limit: int = ...) -> Sequence[Mapping[str, Any]]: ...
