from __future__ import annotations

from collections.abc import Mapping
from typing import MutableMapping, Optional, TypedDict

from deepsearch.infrastructure.cache.cache_manager import CacheManager
from deepsearch.infrastructure.persistence.types import (
    DatabaseServiceProtocol,
    DatabaseSessionProtocol,
    RowDict,
)
from deepsearch.infrastructure.providers.entities.stock import StockEntity, StockMarket, StockStatus
from deepsearch.infrastructure.providers.interfaces.repositories.base import (
    IRepository,
    QueryOptions,
)

class StockRow(TypedDict, total=False):
    symbol: str
    name: str
    market: str
    status: str

class StockRepository(IRepository[StockEntity, str]):
    def __init__(
        self, db_service: DatabaseServiceProtocol, cache_manager: CacheManager | None = ...
    ) -> None: ...
    async def get_by_id(self, symbol: str) -> Optional[StockEntity]: ...
    async def get_all(self, options: QueryOptions | None = ...) -> list[StockEntity]: ...
    async def find(self, criteria: Mapping[str, object]) -> list[StockEntity]: ...
    async def find_one(self, criteria: Mapping[str, object]) -> Optional[StockEntity]: ...
    async def exists(self, symbol: str) -> bool: ...
    async def count(self, criteria: Mapping[str, object] | None = ...) -> int: ...
    async def save(
        self,
        entity: StockEntity,
        *,
        session: DatabaseSessionProtocol | None = ...,  # pragma: no cover - typing only
    ) -> StockEntity: ...
    async def save_many(self, entities: list[StockEntity]) -> list[StockEntity]: ...
    async def update(self, symbol: str, updates: Mapping[str, object]) -> Optional[StockEntity]: ...
    async def delete(self, symbol: str) -> bool: ...
    async def delete_many(self, criteria: Mapping[str, object]) -> int: ...
    async def _insert_entity(
        self,
        session: DatabaseSessionProtocol,
        entity: StockEntity,
    ) -> None: ...
    async def _update_entity(
        self,
        session: DatabaseSessionProtocol,
        symbol: str,
        updates: Mapping[str, object],
    ) -> Optional[StockEntity]: ...
    async def _save_with_session(
        self,
        entity: StockEntity,
        *,
        session: DatabaseSessionProtocol | None = ...,  # pragma: no cover - typing only
    ) -> StockEntity: ...
    async def find_by_market(self, market: StockMarket) -> list[StockEntity]: ...
    async def find_by_status(self, status: StockStatus) -> list[StockEntity]: ...
    async def find_by_industry(self, industry: str) -> list[StockEntity]: ...
    async def find_active_stocks(self) -> list[StockEntity]: ...
    async def search_by_name(self, keyword: str) -> list[StockEntity]: ...
    def _row_to_entity(self, row: RowDict | Mapping[str, object]) -> StockEntity: ...
    def _parse_count(self, value: object) -> int | None: ...
    def _normalize_number(self, value: object) -> float | None: ...
    def _normalize_decimal(self, value: object) -> float | None: ...
    def _prepare_updates(self, updates: Mapping[str, object]) -> MutableMapping[str, object]: ...
