from typing import Any, Iterable, Mapping, Optional

class _MemInfo:
    rss: int
    vms: int
    percent: float
    available: int
    total: int
    used: int
    free: int

class Process:
    pid: int
    def __init__(self, pid: int = ...) -> None: ...
    def memory_info(self) -> _MemInfo: ...
    def cpu_percent(self, interval: float | None = ...) -> float: ...
    def name(self) -> str: ...
    def memory_percent(self) -> float: ...
    def num_threads(self) -> int: ...
    def status(self) -> str: ...
    def exe(self) -> str: ...

class _DiskUsage:
    total: int
    used: int
    free: int
    percent: float

def cpu_percent(interval: float | None = ..., percpu: bool = ...) -> float | list[float]: ...
def cpu_count(logical: bool | None = ...) -> int: ...
def virtual_memory() -> _MemInfo: ...
def disk_usage(path: str) -> _DiskUsage: ...
def sensors_temperatures() -> Mapping[str, Any]: ...
def net_io_counters() -> Any: ...
def net_connections() -> list[Any]: ...
def swap_memory() -> _MemInfo: ...
def cpu_freq() -> Any: ...
def cpu_times() -> Any: ...
def disk_io_counters() -> Any: ...
def disk_partitions() -> list[Any]: ...
def boot_time() -> float: ...
def pids() -> list[int]: ...
def process_iter() -> Iterable[Process]: ...

os: Any
sys: Any

__all__ = [
    "Process",
    "cpu_percent",
    "virtual_memory",
    "disk_usage",
    "sensors_temperatures",
    "cpu_count",
    "net_io_counters",
    "net_connections",
    "swap_memory",
    "cpu_freq",
    "cpu_times",
    "disk_io_counters",
    "disk_partitions",
    "boot_time",
    "pids",
    "process_iter",
]
