from typing import Any

def SMA(*args: Any, **kwargs: Any) -> Any: ...
def EMA(*args: Any, **kwargs: Any) -> Any: ...
def WMA(*args: Any, **kwargs: Any) -> Any: ...
def MACD(*args: Any, **kwargs: Any) -> tuple[Any, Any, Any]: ...
def RSI(*args: Any, **kwargs: Any) -> Any: ...
def BBANDS(*args: Any, **kwargs: Any) -> tuple[Any, Any, Any]: ...
def ATR(*args: Any, **kwargs: Any) -> Any: ...

__all__ = ["SMA", "EMA", "WMA", "MACD", "RSI", "BBANDS", "ATR"]
