from typing import Any

class Cerebro:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addstrategy(self, strategy: type[Any], *args: Any, **kwargs: Any) -> None: ...
    def adddata(self, data: Any) -> None: ...
    def run(self) -> list[Any]: ...

class Strategy:
    params: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class feeds:
    class PandasData:
        params: Any
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...

__all__ = ["Cerebro", "Strategy", "feeds"]
