from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from typing import Any, Awaitable, Callable, Iterable, Protocol, Sequence

class Record(Protocol):
    def __getitem__(self, key: Any) -> Any: ...
    def keys(self) -> Sequence[str]: ...

class Transaction(Protocol):
    async def __aenter__(self) -> Transaction: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: Any | None,
    ) -> bool | None: ...
    async def start(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...

class Connection(Protocol):
    async def __aenter__(self) -> Connection: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: Any | None,
    ) -> bool | None: ...
    async def execute(self, query: str, *args: Any, timeout: float | None = ...) -> str: ...
    async def fetch(self, query: str, *args: Any, timeout: float | None = ...) -> list[Record]: ...
    async def fetchrow(
        self, query: str, *args: Any, timeout: float | None = ...
    ) -> Record | None: ...
    async def fetchval(self, query: str, *args: Any, timeout: float | None = ...) -> Any: ...
    async def executemany(self, command: str, args: Iterable[Sequence[Any]]) -> None: ...
    async def copy_records_to_table(
        self,
        table_name: str,
        *,
        records: Iterable[Sequence[Any]],
        columns: Sequence[str] | None = ...,
        schema_name: str | None = ...,
        timeout: float | None = ...,
    ) -> str: ...
    def transaction(self) -> Transaction: ...

class PoolAcquireContext(AbstractAsyncContextManager[Connection]):
    """Context manager returned by Pool.acquire(). Can also be awaited directly."""

    def __await__(self) -> Any: ...  # 支持 await pool.acquire()
    async def __aenter__(self) -> Connection: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: Any | None,
    ) -> bool | None: ...

class Pool(Protocol):
    # 公共方法
    def acquire(self, *, timeout: float | None = ...) -> PoolAcquireContext: ...
    async def release(self, connection: Connection, *, timeout: float | None = ...) -> None: ...
    async def fetch(self, query: str, *args: Any, timeout: float | None = ...) -> list[Record]: ...
    async def fetchrow(
        self, query: str, *args: Any, timeout: float | None = ...
    ) -> Record | None: ...
    async def fetchval(self, query: str, *args: Any, timeout: float | None = ...) -> Any: ...
    async def executemany(self, command: str, args: Iterable[Iterable[Any]]) -> None: ...
    async def close(self) -> None: ...
    # Pool size methods (public API)
    def get_size(self) -> int: ...
    def get_min_size(self) -> int: ...
    def get_max_size(self) -> int: ...
    def get_idle_size(self) -> int: ...
    # 内部属性 (用于兼容旧代码访问)
    _minsize: int
    _maxsize: int
    _size: int
    _freesize: int
    _queue: Any

async def create_pool(
    dsn: str | None = None,
    *,
    min_size: int = ...,
    max_size: int = ...,
    max_queries: int = ...,
    max_inactive_connection_lifetime: float = ...,
    command_timeout: float | None = ...,
    statement_cache_size: int = ...,
    max_cached_statement_lifetime: int = ...,
    init: Callable[[Connection], Awaitable[None]] | None = ...,
    **kwargs: Any,
) -> Pool: ...

__all__ = ["Record", "Connection", "Pool", "Transaction", "create_pool", "PoolAcquireContext"]
