from __future__ import annotations

from typing import Any, Awaitable, Iterable, Protocol


class Record(Protocol):
    def __getitem__(self, key: Any) -> Any: ...


class Transaction(Protocol):
    async def start(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class Connection(Protocol):
    def __aenter__(self) -> Connection: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: Any | None,
    ) -> bool | None: ...

    async def execute(self, query: str, *args: Any, timeout: float | None = ...) -> str: ...
    async def fetch(self, query: str, *args: Any, timeout: float | None = ...) -> list[Record]: ...
    async def fetchrow(
        self, query: str, *args: Any, timeout: float | None = ...
    ) -> Record | None: ...

    def transaction(self) -> Transaction: ...


class PoolAcquireContext(Protocol):
    def __aenter__(self) -> Awaitable[Connection]: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: Any | None,
    ) -> bool | None: ...


class Pool(Protocol):
    async def acquire(self) -> Connection: ...
    def acquire_context(self) -> PoolAcquireContext: ...
    async def fetch(self, query: str, *args: Any, timeout: float | None = ...) -> list[Record]: ...
    async def fetchrow(
        self, query: str, *args: Any, timeout: float | None = ...
    ) -> Record | None: ...
    async def fetchval(self, query: str, *args: Any, timeout: float | None = ...) -> Any: ...
    async def executemany(self, command: str, args: Iterable[Iterable[Any]]) -> None: ...
    async def close(self) -> None: ...


async def create_pool(*args: Any, **kwargs: Any) -> Pool: ...


__all__ = ["Record", "Connection", "Pool", "Transaction", "create_pool"]
