from typing import Any, Iterator, Mapping, Sequence


class Record(Mapping[str, Any]):
    def __getitem__(self, key: str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...


class Transaction:
    async def start(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class Pool:
    async def close(self) -> None: ...
    async def release(self, connection: "Connection") -> None: ...
    async def acquire(self) -> "Connection": ...
    def get_size(self) -> int: ...
    def get_idle_size(self) -> int: ...


class Connection:
    async def fetch(self, query: str, *args: Any) -> list[Record]: ...
    async def fetchrow(self, query: str, *args: Any) -> Record | None: ...
    async def fetchval(self, query: str, *args: Any) -> Any: ...
    async def execute(self, query: str, *args: Any) -> str: ...
    async def executemany(self, query: str, args: Sequence[Sequence[Any]]) -> None: ...
    def transaction(self) -> Transaction: ...
    async def copy_records_to_table(
        self,
        table_name: str,
        *,
        records: Sequence[Sequence[Any]] | None = ...,
        columns: Sequence[str] | None = ...,
    ) -> str: ...
    async def close(self) -> None: ...


async def connect(dsn: str, *args: Any, **kwargs: Any) -> Connection: ...


async def create_pool(*args: Any, **kwargs: Any) -> Pool: ...


__all__ = ["Connection", "Record", "Transaction", "connect", "create_pool", "Pool"]
