from typing import Any

from . import Connection


class Pool:
    async def close(self) -> None: ...
    async def release(self, connection: Connection) -> None: ...
    async def acquire(self) -> Connection: ...
    def get_size(self) -> int: ...
    def get_idle_size(self) -> int: ...


async def create_pool(*args: Any, **kwargs: Any) -> Pool: ...


__all__ = ["Pool", "create_pool"]
