from typing import Any, Awaitable, AsyncContextManager, Generic, MutableMapping, TypeVar

_T = TypeVar("_T")


class ClientError(Exception): ...


class ClientResponse:
    status: int
    headers: MutableMapping[str, str]

    async def json(self, *args: Any, **kwargs: Any) -> Any: ...
    async def text(self, *args: Any, **kwargs: Any) -> str: ...
    async def read(self) -> bytes: ...
    def release(self) -> None: ...


class _RequestContextManager(Awaitable[_T], AsyncContextManager[_T], Generic[_T]):
    def __await__(self) -> Any: ...
    async def __aenter__(self) -> _T: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...


class ClientSession:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> "ClientSession": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    def get(self, url: str, *args: Any, **kwargs: Any) -> _RequestContextManager[ClientResponse]: ...
    def post(self, url: str, *args: Any, **kwargs: Any) -> _RequestContextManager[ClientResponse]: ...
    async def close(self) -> None: ...


class ClientTimeout:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


__all__ = [
    "ClientSession",
    "ClientTimeout",
    "ClientResponse",
    "ClientError",
]
