from typing import Any, Awaitable, Callable

class ClientSession:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def get(self, url: str, *args: Any, **kwargs: Any) -> Any: ...
    async def post(self, url: str, *args: Any, **kwargs: Any) -> Any: ...
    async def __aenter__(self) -> "ClientSession": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def close(self) -> None: ...

class ClientTimeout:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

__all__ = ["ClientSession", "ClientTimeout"]
