from typing import Any, Generic, Iterable, Mapping, Optional, TypeVar

_T = TypeVar("_T")

class Result(Generic[_T]):
    rowcount: int | None
    def all(self) -> list[_T]: ...
    def first(self) -> _T | None: ...
    def scalar(self) -> _T | None: ...
    def mappings(self) -> "MappingResult": ...


class MappingResult(Result[Mapping[str, Any]]):
    def all(self) -> list[Mapping[str, Any]]: ...
    def first(self) -> Mapping[str, Any] | None: ...

class Engine:
    dialect: Any
    def connect(self) -> Any: ...
    def execute(self, statement: Any, *args: Any, **kwargs: Any) -> Result[Any]: ...
    def begin(self) -> Any: ...

__all__ = ["Result", "MappingResult", "Engine"]
