from typing import Any, Callable, Optional

class AsyncIOScheduler:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def start(self) -> None: ...
    def shutdown(self, wait: bool = True) -> None: ...
    def add_job(
        self,
        func: Callable[..., Any],
        trigger: Any = None,
        args: Optional[tuple[Any, ...]] = None,
        kwargs: Optional[dict[str, Any]] = None,
        id: Optional[str] = None,
        name: Optional[str] = None,
        misfire_grace_time: Optional[int] = None,
        coalesce: bool = True,
        max_instances: int = 1,
        next_run_time: Any = None,
        replace_existing: bool = False,
        **trigger_args: Any,
    ) -> Any: ...
    def remove_job(self, job_id: str) -> None: ...
    def get_jobs(self) -> list[Any]: ...
    def get_job(self, job_id: str) -> Any: ...
    def pause_job(self, job_id: str) -> Any: ...
    def resume_job(self, job_id: str) -> Any: ...
    def modify_job(self, job_id: str, **changes: Any) -> Any: ...
    def reschedule_job(self, job_id: str, trigger: Any = None, **trigger_args: Any) -> Any: ...
    running: bool
