from typing import Any, Iterable, Iterator, Mapping, Optional, Sequence

class Series:
    name: Optional[str]
    dtype: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def to_list(self) -> list[Any]: ...
    def sum(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def shift(self, periods: int = ..., *args: Any, **kwargs: Any) -> "Series": ...

class DataFrame:
    columns: Sequence[str]
    index: Any
    empty: bool
    values: Any
    loc: Any
    def __init__(self, data: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def to_dict(self, orient: str = ...) -> dict[str, Any]: ...
    def to_json(self, *args: Any, **kwargs: Any) -> str: ...
    def head(self, n: int = ...) -> "DataFrame": ...
    def tail(self, n: int = ...) -> "DataFrame": ...
    def iterrows(self) -> Iterable[tuple[Any, Series]]: ...
    def itertuples(self, *args: Any, **kwargs: Any) -> Iterable[Any]: ...
    def assign(self, **kwargs: Any) -> "DataFrame": ...
    def copy(self, deep: bool = ...) -> "DataFrame": ...
    def dropna(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def fillna(self, value: Any = ..., *args: Any, **kwargs: Any) -> "DataFrame": ...
    def rename(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def set_index(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def sort_index(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def ffill(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def bfill(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def abs(self) -> "DataFrame": ...
    def max(self, *args: Any, **kwargs: Any) -> Any: ...
    def min(self, *args: Any, **kwargs: Any) -> Any: ...
    def sum(self, *args: Any, **kwargs: Any) -> Any: ...
    def isnull(self) -> "DataFrame": ...

class Timestamp:
    def __init__(self, value: Any = ...) -> None: ...

class Timedelta:
    def __init__(self, value: Any = ...) -> None: ...

class Index:
    name: Optional[str]
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...

class DatetimeIndex(Index):
    def tz_localize(self, *args: Any, **kwargs: Any) -> "DatetimeIndex": ...

def concat(objs: Sequence[DataFrame], axis: int = ..., join: str = ..., ignore_index: bool = ...) -> DataFrame: ...
def read_csv(filepath: Any, *args: Any, **kwargs: Any) -> DataFrame: ...
def json_normalize(data: Any, *args: Any, **kwargs: Any) -> DataFrame: ...
def to_datetime(arg: Any, *args: Any, **kwargs: Any) -> Series: ...
def date_range(*args: Any, **kwargs: Any) -> DatetimeIndex: ...
def to_numeric(arg: Any, *args: Any, **kwargs: Any) -> Series: ...
def notna(obj: Any) -> bool: ...
def notnull(obj: Any) -> bool: ...

__all__ = [
    "DataFrame",
    "Series",
    "Timestamp",
    "Timedelta",
    "Index",
    "DatetimeIndex",
    "concat",
    "read_csv",
    "json_normalize",
    "to_datetime",
    "date_range",
    "to_numeric",
    "notna",
    "notnull",
]
