from typing import Any, Iterable, Iterator, Mapping, Optional, Sequence


class _IndexAccessor:
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __add__(self, other: Any) -> "Series": ...
    def __radd__(self, other: Any) -> "Series": ...
    def __sub__(self, other: Any) -> "Series": ...
    def __rsub__(self, other: Any) -> "Series": ...
    def __mul__(self, other: Any) -> "Series": ...
    def __rmul__(self, other: Any) -> "Series": ...
    def __truediv__(self, other: Any) -> "Series": ...
    def __rtruediv__(self, other: Any) -> "Series": ...
    def __and__(self, other: Any) -> "Series": ...
    def __rand__(self, other: Any) -> "Series": ...
    def __or__(self, other: Any) -> "Series": ...
    def __ror__(self, other: Any) -> "Series": ...
    def __invert__(self) -> "Series": ...
    def __neg__(self) -> "Series": ...
    def __lt__(self, other: Any) -> "Series": ...
    def __le__(self, other: Any) -> "Series": ...
    def __gt__(self, other: Any) -> "Series": ...
    def __ge__(self, other: Any) -> "Series": ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...


class Rolling:
    def mean(self, *args: Any, **kwargs: Any) -> "Series": ...
    def std(self, *args: Any, **kwargs: Any) -> "Series": ...
    def min(self, *args: Any, **kwargs: Any) -> "Series": ...
    def max(self, *args: Any, **kwargs: Any) -> "Series": ...
    def sum(self, *args: Any, **kwargs: Any) -> "Series": ...
    def apply(self, func: Any, *args: Any, **kwargs: Any) -> "Series": ...


class Expanding:
    def max(self, *args: Any, **kwargs: Any) -> "Series": ...
    def mean(self, *args: Any, **kwargs: Any) -> "Series": ...
    def sum(self, *args: Any, **kwargs: Any) -> "Series": ...


class EWM:
    def mean(self, *args: Any, **kwargs: Any) -> "Series": ...


class Series:
    name: Optional[str]
    dtype: Any
    index: Any
    iloc: _IndexAccessor
    values: Any
    empty: bool
    dt: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __add__(self, other: Any) -> "Series": ...
    def __radd__(self, other: Any) -> "Series": ...
    def __sub__(self, other: Any) -> "Series": ...
    def __rsub__(self, other: Any) -> "Series": ...
    def __mul__(self, other: Any) -> "Series": ...
    def __rmul__(self, other: Any) -> "Series": ...
    def __truediv__(self, other: Any) -> "Series": ...
    def __rtruediv__(self, other: Any) -> "Series": ...
    def __floordiv__(self, other: Any) -> "Series": ...
    def __rfloordiv__(self, other: Any) -> "Series": ...
    def __pow__(self, other: Any) -> "Series": ...
    def __rpow__(self, other: Any) -> "Series": ...
    def __neg__(self) -> "Series": ...
    def __pos__(self) -> "Series": ...
    def __and__(self, other: Any) -> "Series": ...
    def __rand__(self, other: Any) -> "Series": ...
    def __or__(self, other: Any) -> "Series": ...
    def __ror__(self, other: Any) -> "Series": ...
    def __invert__(self) -> "Series": ...
    def __lt__(self, other: Any) -> "Series": ...
    def __le__(self, other: Any) -> "Series": ...
    def __gt__(self, other: Any) -> "Series": ...
    def __ge__(self, other: Any) -> "Series": ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def abs(self) -> "Series": ...
    def astype(self, dtype: Any, *args: Any, **kwargs: Any) -> "Series": ...
    def clip(self, lower: Any | None = ..., upper: Any | None = ..., *args: Any, **kwargs: Any) -> "Series": ...
    def copy(self) -> "Series": ...
    def cumsum(self) -> "Series": ...
    def cumprod(self) -> "Series": ...
    def diff(self, periods: int = ..., *args: Any, **kwargs: Any) -> "Series": ...
    def dropna(self, *args: Any, **kwargs: Any) -> "Series": ...
    def expanding(self, *args: Any, **kwargs: Any) -> Expanding: ...
    def ewm(self, *args: Any, **kwargs: Any) -> EWM: ...
    def fillna(self, value: Any = ..., *args: Any, **kwargs: Any) -> "Series": ...
    def ffill(self, *args: Any, **kwargs: Any) -> "Series": ...
    def bfill(self, *args: Any, **kwargs: Any) -> "Series": ...
    def head(self, n: int = ...) -> "Series": ...
    def isna(self) -> "Series": ...
    def items(self) -> Iterator[tuple[Any, Any]]: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    def max(self, *args: Any, **kwargs: Any) -> Any: ...
    def mean(self, *args: Any, **kwargs: Any) -> Any: ...
    def median(self, *args: Any, **kwargs: Any) -> Any: ...
    def min(self, *args: Any, **kwargs: Any) -> Any: ...
    def pct_change(self, *args: Any, **kwargs: Any) -> "Series": ...
    def mode(self, dropna: bool = ...) -> "Series": ...
    def quantile(self, q: float, *args: Any, **kwargs: Any) -> Any: ...
    def replace(self, to_replace: Any, value: Any | None = ..., *args: Any, **kwargs: Any) -> "Series": ...
    def rolling(self, window: Any, min_periods: Any | None = ..., *args: Any, **kwargs: Any) -> Rolling: ...
    def shift(self, periods: int = ..., *args: Any, **kwargs: Any) -> "Series": ...
    def skew(self, *args: Any, **kwargs: Any) -> Any: ...
    def kurtosis(self, *args: Any, **kwargs: Any) -> Any: ...
    def std(self, *args: Any, **kwargs: Any) -> Any: ...
    def sum(self, *args: Any, **kwargs: Any) -> Any: ...
    def tail(self, n: int = ...) -> "Series": ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_frame(self, name: str | None = ...) -> "DataFrame": ...
    def to_list(self) -> list[Any]: ...
    def tolist(self) -> list[Any]: ...
    def unique(self) -> list[Any]: ...
    def where(self, cond: Any, other: Any = ..., *args: Any, **kwargs: Any) -> "Series": ...
    def map(self, arg: Any, na_action: str | None = ...) -> "Series": ...

class DataFrame:
    columns: Any
    index: Any
    empty: bool
    values: Any
    loc: Any
    iloc: Any
    def __init__(self, data: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def to_dict(self, orient: str = ...) -> dict[str, Any]: ...
    def to_json(self, *args: Any, **kwargs: Any) -> str: ...
    def head(self, n: int = ...) -> "DataFrame": ...
    def tail(self, n: int = ...) -> "DataFrame": ...
    def iterrows(self) -> Iterable[tuple[Any, Series]]: ...
    def itertuples(self, *args: Any, **kwargs: Any) -> Iterable[Any]: ...
    def assign(self, **kwargs: Any) -> "DataFrame": ...
    def copy(self, deep: bool = ...) -> "DataFrame": ...
    def dropna(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def drop_duplicates(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def fillna(self, value: Any = ..., *args: Any, **kwargs: Any) -> "DataFrame": ...
    def rename(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def set_index(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def sort_index(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def sort_values(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def ffill(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def bfill(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def abs(self) -> "DataFrame": ...
    def max(self, *args: Any, **kwargs: Any) -> Any: ...
    def min(self, *args: Any, **kwargs: Any) -> Any: ...
    def sum(self, *args: Any, **kwargs: Any) -> Any: ...
    def isnull(self) -> "DataFrame": ...
    def reset_index(self, *args: Any, **kwargs: Any) -> "DataFrame": ...
    def select_dtypes(self, include: Any = ..., exclude: Any = ...) -> "DataFrame": ...
    def rolling(self, window: Any, *args: Any, **kwargs: Any) -> Rolling: ...
    def groupby(self, *args: Any, **kwargs: Any) -> Any: ...

    @classmethod
    def from_dict(cls, data: Any, *args: Any, **kwargs: Any) -> "DataFrame": ...

from datetime import datetime


class Timestamp:
    def __init__(self, value: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def now(tz: Any | None = ...) -> "Timestamp": ...
    def isoformat(self) -> str: ...
    def to_pydatetime(self) -> datetime: ...

class Timedelta:
    def __init__(self, value: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def __le__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...

class Index:
    name: Optional[str]
    values: Any
    is_monotonic_increasing: bool
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def duplicated(self, *args: Any, **kwargs: Any) -> Any: ...

class DatetimeIndex(Index):
    def tz_localize(self, *args: Any, **kwargs: Any) -> "DatetimeIndex": ...
    def duplicated(self, *args: Any, **kwargs: Any) -> Any: ...
    values: Any
    def difference(self, other: Any) -> "DatetimeIndex": ...

class ExcelWriter:
    def __init__(self, path: Any, *args: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> "ExcelWriter": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    def save(self) -> None: ...

class _TypesModule:
    def is_datetime64_any_dtype(self, arr: Any) -> bool: ...
    def is_numeric_dtype(self, arr: Any) -> bool: ...


class _APIModule:
    types: _TypesModule


api: _APIModule

def concat(objs: Sequence[Any], axis: int = ..., join: str = ..., ignore_index: bool = ...) -> DataFrame: ...
def read_csv(filepath: Any, *args: Any, **kwargs: Any) -> DataFrame: ...
def json_normalize(data: Any, *args: Any, **kwargs: Any) -> DataFrame: ...
def to_datetime(arg: Any, *args: Any, **kwargs: Any) -> Series: ...
def date_range(*args: Any, **kwargs: Any) -> DatetimeIndex: ...
def bdate_range(*args: Any, **kwargs: Any) -> DatetimeIndex: ...
def to_numeric(arg: Any, *args: Any, **kwargs: Any) -> Series: ...
def notna(obj: Any) -> bool: ...
def notnull(obj: Any) -> bool: ...
def cut(x: Any, bins: Any, *args: Any, **kwargs: Any) -> Series: ...
def to_timedelta(arg: Any, *args: Any, **kwargs: Any) -> Series: ...
def isna(obj: Any) -> bool: ...

NA: Any

__all__ = [
    "DataFrame",
    "Series",
    "Timestamp",
    "Timedelta",
    "Index",
    "DatetimeIndex",
    "Rolling",
    "Expanding",
    "EWM",
    "ExcelWriter",
    "api",
    "concat",
    "read_csv",
    "json_normalize",
    "to_datetime",
    "date_range",
    "bdate_range",
    "to_numeric",
    "notna",
    "notnull",
    "cut",
    "to_timedelta",
    "isna",
    "NA",
]
