"""Utility script to summarize mypy error counts per file."""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path
from typing import Iterable

ERROR_PATTERN = re.compile(r"^(?P<file>[^:]+):(?P<line>\d+): error: (?P<message>.*)")


def parse_errors(lines: Iterable[str]) -> Counter[str]:
    counter: Counter[str] = Counter()
    for line in lines:
        match = ERROR_PATTERN.match(line.strip())
        if match:
            counter[match.group("file")] += 1
    return counter


def main() -> None:
    parser = argparse.ArgumentParser(description="Aggregate mypy errors from a log file")
    parser.add_argument(
        "log",
        type=Path,
        help="Path to the log file generated by a command such as `uv run mypy deepsearch > mypy.log`",
    )
    args = parser.parse_args()
    if not args.log.exists():
        raise SystemExit(f"Log file not found: {args.log}")

    lines = args.log.read_text(encoding="utf-8", errors="ignore").splitlines()
    counter = parse_errors(lines)

    total = sum(counter.values())
    for file, count in counter.most_common():
        print(f"{count:4} {file}")
    print(f"Total: {total}")


if __name__ == "__main__":
    main()
